version: '3.8'
services:
  arachni:
    image: 'csalab/arachni:latest'
    hostname: arachni.csaf.lab
    restart: always
    build:
      context: ./build/
      dockerfile: arachni.Dockerfile
    ports:
      - 0.0.0.0:9292:9292
    networks:
      dast:
        ipv4_address: 10.0.10.10

networks:
  dast:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.10.0/24
          gateway: 10.0.10.1